version: '3.8'
services:
  database:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=revisa_smart
  queue:
    image: 'redis'
    ports:
      - 6379:6379
